### ISSUE TITLE
Bot removes highlighted lines in the URLs

### ISSUE THREAD

**Issue by maks-rafalko** [kapillamba4/permalink-bot#1]
Hello,

could you please look at this diff of the bot's changes:

<img width="640" alt="bot" src="https://user-images.githubusercontent.com/3725595/45921202-fa28b880-beb9-11e8-828a-1e2195062e05.png">

Seems like it removes hightlighted lines and the `#` sign.

Affected comment: https://github.com/infection/infection/issues/486#issuecomment-423764688

/cc @sidz

**Comment by kapillamba4** [comment]
https://github.com/infection/infection/blob/c77dbe8da2bdea64ae761c94fe7962abeca04362/src/Process/MutantProcess.php#L86-L105

**Comment by kapillamba4** [comment]
https://github.com/infection/infection/blob/c77dbe8da2bdea64ae761c94fe7962abeca04362/src/Process/MutantProcess.php

https://github.com/infection/infection/blob/32a399d214e384feaed79775ce460b9ada6da952/src/TestFramework/PhpUnit/Adapter/PhpUnitAdapter.php

**Comment by kapillamba4** [comment]
https://github.com/infection/infection/blob/c77dbe8da2bdea64ae761c94fe7962abeca04362/src/Process/MutantProcess.php#L86-L105

https://github.com/infection/infection/blob/32a399d214e384feaed79775ce460b9ada6da952/src/TestFramework/PhpUnit/Adapter/PhpUnitAdapter.php#L22-L42

**Comment by kapillamba4** [comment]
https://github.com/kapillamba4/permalink-bot/blob/master/index.js#L26-L34
https://github.com/kapillamba4/permalink-bot/blob/master/index.js#L36

**Comment by kapillamba4** [comment]
https://github.com/kapillamba4/permalink-bot/blob/master/index.js#L1-L57

**Comment by kapillamba4** [comment]
https://github.com/kapillamba4/permalink-bot/blob/5e4138e335f3ba745b71eaffbbf6d2a7c808090e/index.js#L26-L34
https://github.com/kapillamba4/permalink-bot/blob/5e4138e335f3ba745b71eaffbbf6d2a7c808090e/index.js#L1-L57

**Comment by kapillamba4** [comment]
@borNfreee, works now for `#` in the github url

**Comment by kapillamba4** [comment]
https://github.com/kapillamba4/permalink-bot/blob/master/index.js
